// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs4uUrp87y9gUex_fK042UFuQ3n1KNEF0',
    appId: '1:95738155674:ios:5798aaed21df2315b68523',
    messagingSenderId: '95738155674',
    projectId: 'complaint-app-1a1e4',
    storageBucket: 'complaint-app-1a1e4.firebasestorage.app',
    iosBundleId: 'com.example.complaintApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeoNoIR56VMuIYx-nOGN_bX5BW8w-fLUM',
    appId: '1:95738155674:web:27ed0b51f737e3e1b68523',
    messagingSenderId: '95738155674',
    projectId: 'complaint-app-1a1e4',
    authDomain: 'complaint-app-1a1e4.firebaseapp.com',
    storageBucket: 'complaint-app-1a1e4.firebasestorage.app',
    measurementId: 'G-VKTM6LX42H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs4uUrp87y9gUex_fK042UFuQ3n1KNEF0',
    appId: '1:95738155674:ios:5798aaed21df2315b68523',
    messagingSenderId: '95738155674',
    projectId: 'complaint-app-1a1e4',
    storageBucket: 'complaint-app-1a1e4.firebasestorage.app',
    iosBundleId: 'com.example.complaintApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbvCzD5FNBuBw0eCLA-nr4Hu5qnAu3OCo',
    appId: '1:95738155674:android:f77518290f404042b68523',
    messagingSenderId: '95738155674',
    projectId: 'complaint-app-1a1e4',
    storageBucket: 'complaint-app-1a1e4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeoNoIR56VMuIYx-nOGN_bX5BW8w-fLUM',
    appId: '1:95738155674:web:af0d9c8b2470ed6cb68523',
    messagingSenderId: '95738155674',
    projectId: 'complaint-app-1a1e4',
    authDomain: 'complaint-app-1a1e4.firebaseapp.com',
    storageBucket: 'complaint-app-1a1e4.firebasestorage.app',
    measurementId: 'G-VTJE4L4LEP',
  );

}